spring:
  liquibase:
    enabled: true
  datasource:
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/OnlineShop
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    com.example.practice: error
  file:
    path: ./logs
    name: ${logging.file.path}/online-shop-app.log
  threshold:
    file: ERROR